"use client";

import { useState } from "react";
import { Download, FileCode2, FileText } from "lucide-react";

interface ExportMenuProps {
    braille?: string;
    mathml?: string;
}

export default function ExportMenu({ braille, mathml }: ExportMenuProps) {
    const [isOpen, setIsOpen] = useState(false);

    // If neither export format was generated by the AI, don't show the menu
    if (!braille && !mathml) return null;

    const handleDownload = (content: string, filename: string, mimeType: string) => {
        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        setIsOpen(false);
    };

    return (
        <div className="relative">
            <button
                onClick={() => setIsOpen(!isOpen)}
                className="flex items-center gap-2 py-3 px-6 bg-white/10 hover:bg-white/20 border border-white/20 text-white rounded-xl font-bold transition-all"
                aria-expanded={isOpen}
                aria-haspopup="true"
                aria-label="Export options menu"
            >
                <Download size={20} />
                Export For Assistive Tech
            </button>

            {isOpen && (
                <div
                    className="absolute top-full mt-2 w-full min-w-[200px] glass-panel rounded-xl border border-white/10 shadow-2xl overflow-hidden z-50 animate-in fade-in slide-in-from-top-2"
                    role="menu"
                >
                    <div className="p-2 space-y-1">
                        {braille && (
                            <button
                                onClick={() => handleDownload(braille, "equation.brf", "text/plain")}
                                className="w-full flex items-center gap-3 p-3 hover:bg-white/10 rounded-lg text-left transition-colors text-white"
                                role="menuitem"
                            >
                                <FileText size={18} className="text-[var(--color-primary)]" />
                                <div>
                                    <div className="font-bold text-sm">Nemeth Braille (.brf)</div>
                                    <div className="text-xs text-gray-400">For refreshable displays</div>
                                </div>
                            </button>
                        )}

                        {mathml && (
                            <button
                                onClick={() => handleDownload(mathml, "equation.xml", "application/xml")}
                                className="w-full flex items-center gap-3 p-3 hover:bg-white/10 rounded-lg text-left transition-colors text-white"
                                role="menuitem"
                            >
                                <FileCode2 size={18} className="text-[var(--color-primary)]" />
                                <div>
                                    <div className="font-bold text-sm">MathML (.xml)</div>
                                    <div className="text-xs text-gray-400">For screen readers & web</div>
                                </div>
                            </button>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
}
